import StyleDictionary from "style-dictionary";
import { readFileSync } from "node:fs";
import { transforms } from "style-dictionary/enums";

const { attributeCti, nameKebab } = transforms;

const activeTokens = [
  "background-page",
  "background-surface",
  "background-elevated",
  "background-muted",
  "text-primary",
  "text-secondary",
  "text-muted",
  "text-inverse",
  "border-default",
  "border-strong",
  "border-focus",
  "action-primary",
  "action-primary-hover",
  "action-secondary",
  "action-secondary-hover",
  "link-default",
  "link-hover",
  "feedback-success",
  "feedback-success-subtle",
  "feedback-warning",
  "feedback-warning-subtle",
  "feedback-error",
  "feedback-error-subtle"
];

const componentTokens = JSON.parse(
  readFileSync("src/design-system/tokens/component/component.json", "utf8")
);

function tokenName(...parts: string[]) {
  return parts.join("-");
}

function pathToKebab(path: string[]) {
  return path
    .map((part) => part.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase())
    .join("-");
}

function componentCssName(path: string[]) {
  const [, componentName, group, ...rest] = path;

  if (group === "variant") {
    return pathToKebab([componentName, ...rest]);
  }

  if (group === "root") {
    return pathToKebab([componentName, ...rest]);
  }

  return pathToKebab([componentName, group, ...rest]);
}

function cssValue(value: string) {
  const activeThemeMatch = value.match(/^\{theme\.active\.(.+)\}$/);

  if (activeThemeMatch) {
    return `var(--color-${pathToKebab(activeThemeMatch[1].split("."))})`;
  }

  const tokenReferenceMatch = value.match(/^\{(.+)\}$/);

  if (!tokenReferenceMatch) {
    return value;
  }

  return `var(--${pathToKebab(tokenReferenceMatch[1].split("."))})`;
}

function collectComponentTokens(
  node: unknown,
  path: string[] = [],
  tokens: { name: string; value: string }[] = []
) {
  if (!node || typeof node !== "object") {
    return tokens;
  }

  if (
    "type" in node &&
    "value" in node &&
    typeof node.value === "string"
  ) {
    tokens.push({
      name: componentCssName(path),
      value: cssValue(node.value)
    });

    return tokens;
  }

  Object.entries(node).forEach(([key, value]) => {
    collectComponentTokens(value, [...path, key], tokens);
  });

  return tokens;
}

function activeThemeBlock({
  selector,
  theme,
  mode,
  tokenValues
}: {
  selector: string;
  theme: "default" | "brown";
  mode: "light" | "dark";
  tokenValues: Map<string, string>;
}) {
  const lines = [`${selector} {`];

  activeTokens.forEach((token) => {
    const themeParts = token.split("-");
    const themeToken = tokenName("theme", theme, mode, ...themeParts);
    const defaultToken = tokenName("theme", "default", mode, ...themeParts);
    const value = tokenValues.get(themeToken) ?? tokenValues.get(defaultToken);

    if (value) {
      lines.push(`  --color-${token}: ${value};`);
    }
  });

  lines.push("}");
  return lines.join("\n");
}

StyleDictionary.registerFormat({
  name: "ayanna/active-theme",
  format: ({ dictionary }) => {
    const tokenValues = new Map(
      dictionary.allTokens.map((token) => [token.name, String(token.value)])
    );

    return [
      "/* Generated by Style Dictionary. */",
      "",
      "/* Default Light */",
      activeThemeBlock({
        selector: ':root,\n[data-theme="default"]',
        theme: "default",
        mode: "light",
        tokenValues
      }),
      "",
      "/* Default Dark */",
      activeThemeBlock({
        selector: '.dark[data-theme="default"],\n[data-theme="default"].dark',
        theme: "default",
        mode: "dark",
        tokenValues
      }),
      "",
      "/* Brown Light - inherits default tokens, then applies brown overrides. */",
      activeThemeBlock({
        selector: '[data-theme="brown"]',
        theme: "brown",
        mode: "light",
        tokenValues
      }),
      "",
      "/* Brown Dark - inherits default tokens, then applies brown overrides. */",
      activeThemeBlock({
        selector: '.dark[data-theme="brown"],\n[data-theme="brown"].dark',
        theme: "brown",
        mode: "dark",
        tokenValues
      }),
      ""
    ].join("\n");
  }
});

StyleDictionary.registerFormat({
  name: "ayanna/component-theme",
  format: () => {
    const componentLines = collectComponentTokens(componentTokens).map(
      (token) => `  --${token.name}: ${token.value};`
    );

    return [
      "/* Generated by Style Dictionary. */",
      "",
      "/* Component Runtime Tokens */",
      ":root {",
      ...componentLines,
      "}",
      ""
    ].join("\n");
  }
});

StyleDictionary.registerFormat({
  name: "ayanna/foundation-theme",
  format: ({ dictionary }) => {
    const foundationLines = dictionary.allTokens
      .filter((token) => token.filePath.includes("/tokens/foundation/"))
      .map((token) => `  --${token.name}: ${token.value};`);

    return [
      "/* Generated by Style Dictionary. */",
      "",
      "/* Foundation Tokens */",
      ":root {",
      ...foundationLines,
      "}",
      ""
    ].join("\n");
  }
});

export default {
  source: [
    "src/design-system/tokens/colors/**/*.json",
    "src/design-system/tokens/foundation/**/*.json"
  ],
  platforms: {
    css: {
      transforms: [attributeCti, nameKebab],
      buildPath: "src/design-system/tokens/generated/",
      files: [
        {
          destination: "foundation-theme.css",
          format: "ayanna/foundation-theme"
        },
        {
          destination: "active-theme.css",
          format: "ayanna/active-theme"
        },
        {
          destination: "component-theme.css",
          format: "ayanna/component-theme"
        }
      ]
    }
  }
};
