import StyleDictionary from "style-dictionary";
import { readFileSync } from "node:fs";
import { transforms } from "style-dictionary/enums";

const { attributeCti, nameKebab } = transforms;

const activeTokens = [
  "background-page",
  "background-surface",
  "background-elevated",
  "background-muted",
  "text-primary",
  "text-secondary",
  "text-muted",
  "text-inverse",
  "border-default",
  "border-strong",
  "border-focus",
  "action-primary",
  "action-primary-hover",
  "action-secondary",
  "action-secondary-hover",
  "link-default",
  "link-hover",
  "feedback-success",
  "feedback-success-subtle",
  "feedback-warning",
  "feedback-warning-subtle",
  "feedback-error",
  "feedback-error-subtle"
];

const componentTokens = JSON.parse(
  readFileSync("src/design-system/tokens/component/component.json", "utf8")
);

function tokenName(...parts: string[]) {
  return parts.join("-");
}

function hasToken(tokenNames: Set<string>, ...parts: string[]) {
  return tokenNames.has(tokenName(...parts));
}

function pathToKebab(path: string[]) {
  return path
    .map((part) => part.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase())
    .join("-");
}

function componentCssName(path: string[]) {
  const [, componentName, group, ...rest] = path;

  if (group === "variant") {
    return pathToKebab([componentName, ...rest]);
  }

  if (group === "root") {
    return pathToKebab([componentName, ...rest]);
  }

  return pathToKebab([componentName, group, ...rest]);
}

function cssValue(value: string) {
  const match = value.match(/^\{theme\.active\.(.+)\}$/);

  if (!match) {
    return value;
  }

  return `var(--color-${pathToKebab(match[1].split("."))})`;
}

function collectComponentColorTokens(
  node: unknown,
  path: string[] = [],
  tokens: { name: string; value: string }[] = []
) {
  if (!node || typeof node !== "object") {
    return tokens;
  }

  if (
    "type" in node &&
    "value" in node &&
    node.type === "color" &&
    typeof node.value === "string"
  ) {
    tokens.push({
      name: componentCssName(path),
      value: cssValue(node.value)
    });

    return tokens;
  }

  Object.entries(node).forEach(([key, value]) => {
    collectComponentColorTokens(value, [...path, key], tokens);
  });

  return tokens;
}

function activeThemeBlock({
  selector,
  theme,
  mode,
  tokenNames
}: {
  selector: string;
  theme: "default" | "brown";
  mode: "light" | "dark";
  tokenNames: Set<string>;
}) {
  const lines = [`${selector} {`];

  activeTokens.forEach((token) => {
    const themeParts = token.split("-");
    const sourceTheme = hasToken(tokenNames, "theme", theme, mode, ...themeParts)
      ? theme
      : "default";

    lines.push(
      `  --color-${token}: var(--theme-${sourceTheme}-${mode}-${token});`
    );
  });

  lines.push("}");
  return lines.join("\n");
}

StyleDictionary.registerFormat({
  name: "ayanna/active-theme",
  format: ({ dictionary }) => {
    const tokenNames = new Set(dictionary.allTokens.map((token) => token.name));
    const tokenLines = dictionary.allTokens
      .filter((token) => token.type === "color")
      .map((token) => `  --${token.name}: ${token.value};`);

    const componentLines = collectComponentColorTokens(componentTokens).map(
      (token) => `  --${token.name}: ${token.value};`
    );

    return [
      "/* Generated by Style Dictionary. */",
      "",
      ":root {",
      ...tokenLines,
      "}",
      "",
      "/* Default Light */",
      activeThemeBlock({
        selector: ':root,\n[data-theme="default"]',
        theme: "default",
        mode: "light",
        tokenNames
      }),
      "",
      "/* Default Dark */",
      activeThemeBlock({
        selector: '.dark[data-theme="default"],\n[data-theme="default"].dark',
        theme: "default",
        mode: "dark",
        tokenNames
      }),
      "",
      "/* Brown Light - inherits default tokens, then applies brown overrides. */",
      activeThemeBlock({
        selector: '[data-theme="brown"]',
        theme: "brown",
        mode: "light",
        tokenNames
      }),
      "",
      "/* Brown Dark - inherits default tokens, then applies brown overrides. */",
      activeThemeBlock({
        selector: '.dark[data-theme="brown"],\n[data-theme="brown"].dark',
        theme: "brown",
        mode: "dark",
        tokenNames
      }),
      "",
      "/* Component Runtime Tokens */",
      ":root {",
      ...componentLines,
      "}",
      ""
    ].join("\n");
  }
});

export default {
  source: ["src/design-system/tokens/colors/**/*.json"],
  platforms: {
    css: {
      transforms: [attributeCti, nameKebab],
      buildPath: "src/design-system/tokens/generated/",
      files: [
        {
          destination: "active-theme.css",
          format: "ayanna/active-theme"
        }
      ]
    }
  }
};
