import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BarChart2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  Cpu,
  Download,
  FileText,
  Github,
  GripVertical,
  Linkedin,
  Mail,
  Menu,
  Minus,
  Moon,
  MoreHorizontal,
  PanelLeft,
  Pen,
  Play,
  Rocket,
  Search,
  Settings,
  Sun,
  X,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "./types";

// The registry is the only lucide-react dependency in the design-system icon API.
// App code depends on stable design-system names, so replacing Lucide or adding a
// custom SVG later only requires changing this map instead of every call site.
export const iconRegistry = {
  github: Github,
  linkedin: Linkedin,
  mail: Mail,
  download: Download,
  "external-link": ArrowUpRight,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  "arrow-up-right": ArrowUpRight,
  "bar-chart-2": BarChart2,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  close: X,
  cpu: Cpu,
  "file-text": FileText,
  "grip-vertical": GripVertical,
  menu: Menu,
  minus: Minus,
  moon: Moon,
  "more-horizontal": MoreHorizontal,
  "panel-left": PanelLeft,
  pen: Pen,
  play: Play,
  rocket: Rocket,
  search: Search,
  settings: Settings,
  sun: Sun,
} satisfies Record<IconName, LucideIcon>;
