export type IconSize = "xs" | "sm" | "md" | "lg" | "xl";

export type IconName =
  | "github"
  | "linkedin"
  | "mail"
  | "download"
  | "external-link"
  | "arrow-right"
  | "arrow-left"
  | "arrow-up-right"
  | "bar-chart-2"
  | "check"
  | "chevron-down"
  | "chevron-left"
  | "chevron-right"
  | "chevron-up"
  | "circle"
  | "close"
  | "cpu"
  | "file-text"
  | "grip-vertical"
  | "menu"
  | "minus"
  | "moon"
  | "more-horizontal"
  | "panel-left"
  | "pen"
  | "play"
  | "rocket"
  | "search"
  | "settings"
  | "sun";
